### ISSUE TITLE
Issues with soft keys.

### ISSUE THREAD

**Issue by LeightonW87** [Toonlink3000/KaiOS-Object#1]
I'm trying to make a game using you extension for Clickteam Fusion 2.5 and discovered some issues with the kaios.js file.

When i was using it I discovered the code was getting a uncaught exception, this is because "version" wasn't being defined, anothe issue was that the softkey code was broken, there was no breaks in the case statements so both left and right softkey code was triggering at the same time.

I've attached my modified kaios.js file. 
[KaiOS.js.zip](https://github.com/user-attachments/files/15955670/KaiOS.js.zip)

**Comment by Toonlink3000** [comment]
Hello! 
Thanks for catching my mistakes. Now that I look back there is a lot of stuff in there that isn't ideal (various pythonisms like == instead of === and var instead of let in some places).

I added the breaks in the soft key switch and i added in the code that should've retrieved the version string in the constructor.

The new version is in the repo, let me know if something else needs to be fixed.

I'm very happy someone found use for this extension since I didn't.

**Comment by LeightonW87** [comment]
No worries, mainly needed it for the softkeys support and was glad someone made an extension. Will likely use it for the other features at some point, will test them at some point and will let you know of any major issues if i find them..
